#!/usr/bin/env node
import packageJson from './package.json' assert { type: 'json' };
import { program } from 'commander';
import fs from 'fs';
import path from 'path';
import {url} from 'cute-fs';

let pr = false;
let gcf = false;
let packageName;
let cwd;
let srcDirPath;
function main()
{
    program.description("npm init shorthand").arguments("[optionalArg]").action((optionalArg) =>
    {
        switch (optionalArg) {
            case 'pr':
                pr = !pr;
                break;
            case 'gcf':
                gcf = !gcf;
                break;
        }
    });
    program.parse(process.argv);

    cwd = process.cwd();
    packageName = path.basename(cwd);
    srcDirPath = path.join(cwd, 'src');
    fs.mkdirSync(srcDirPath, {recursive: true});
    createPackageJson();
    createIndexJs();
    createCliJs();
    createNpmIgnore();
    createGitIgnore();
    createReadMe();
    createTestJs();
    createDotNpmrc();

    console.log(`Project initialization completed with cute-npm-init`);
}

function createPackageJson()
{
    console.log("cute-npm-init v" + packageJson.version);
    const packageJsonPath = path.join(cwd, 'package.json');
    if (!fs.existsSync(packageJsonPath)) {
        const packageJson = {
            name: packageName, version: "0.1.0", description: "Experimental piercer stronghold. No tests.", type: "module", main: "src/index.js", bin: {
                [packageName]: "src/cli.js"
            }, scripts: {
                "postinstall": "echo 'Installed.`", "test": "node ./src/test.js", "cli": "node ./src/cli.js"
            }, exports: "./src/index.js", keywords: ["cute"], author: "", license: "CC-BY-4.0", homepage: pr ? 'https://bit.ly/incessant-vibration' : '', repository: pr ? `git+https://github.com/planetrenox/${packageName}.git` : `git+https://github.com/user/${packageName}.git`

        };
        fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
        console.log("Generated package.json with cute defaults.");
    }
}

function createIndexJs()
{
    const indexJsPath = path.join(srcDirPath, 'index.js');
    if (!fs.existsSync(indexJsPath)) {
        fs.writeFileSync(indexJsPath, `// import dotenv from 'dotenv'; dotenv.config(); // process.env.EDIT_ME
export const testMe = () => console.log("test.");
`);
        console.log("Generated index.js with cute defaults. For quick testing: npm run test");
    }
}

function createCliJs()
{
    const cliJsPath = path.join(srcDirPath, 'cli.js');
    if (!fs.existsSync(cliJsPath)) {
        const cliJsContent = `#!/usr/bin/env node
//import { program } from 'commander';
console.log("Running", "${packageName}!");
console.log("or npm run test");

// program
// .description("accepts 0 or 1 arguments")
// .arguments("[optionalArg]")
// .action((optionalArg) => {
//  switch (optionalArg) {
//             case 'op1':
//                 !true = !false;
//                 break;
//             case 'op2':
//                 !true = !false;
//                 break;
//         }
// });
// program.parse(process.argv);
`;
        fs.writeFileSync(cliJsPath, cliJsContent);
        console.log("Generated cli.js with CLI functionality. For placeholder testing: npm run cli");
    }
}

function createNpmIgnore()
{
    const npmIgnorePath = path.join(cwd, '.npmignore');
    if (!fs.existsSync(npmIgnorePath)) {
        const npmIgnoreContent = `**/.DS_Store
**/Thumbs.db
*.log
node_modules/
.env
coverage/
dist/
*.test.js
*.spec.js
tests/
__tests__/
test/
.git/
.github/
.gitlab/
.idea/
*.config.js
`;
        fs.writeFileSync(npmIgnorePath, npmIgnoreContent);
        console.log("Generated .npmignore with cute defaults.");
    }
}

function createGitIgnore()
{
    const gitIgnorePath = path.join(cwd, '.gitignore');
    if (!fs.existsSync(gitIgnorePath)) {
        const gitIgnoreContent = `**/.git
package-lock.json
        
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
`;
        fs.writeFileSync(gitIgnorePath, gitIgnoreContent);
        console.log("Generated .gitignore with cute npm defaults.");
    }
}

function createReadMe()
{
    const readMePath = path.join(cwd, 'readme.md');
    if (!fs.existsSync(readMePath)) {
        const readMeContent = `[available on npmjs](https://www.npmjs.com/package/${packageName})
# ${packageName}


A tiny description.


## Features


- Item

- Item

- Item


## Why


This package solves ...


## Getting Started


### Installation


1. Install ${packageName} locally.


   \`\`\`
   npm install ${packageName}
   npm install --global ${packageName}
   \`\`\`


### Usage


   \`\`\`JavaScript
   import default from '${packageName}';
   \`\`\`
   
![image of banner](https://fakeimg.pl/730x380)
`;
        fs.writeFileSync(readMePath, readMeContent);
        console.log("Generated readme.md with cute defaults.");
    }
}

function createTestJs()
{

    const testJsPath = path.join(srcDirPath, 'test.js');
    if (!fs.existsSync(testJsPath)) {
        const testJsContent = `// import dotenv from 'dotenv'; dotenv.config(); // process.env.EDIT_ME // import { _, __ } from 'cute-con';
import { testMe } from './index.js';

const test = () => console.log("tested test.js");

test();
testMe();
`;
        fs.writeFileSync(testJsPath, testJsContent);
        console.log("Generated test.js with tests: npm run test");
    }
}

function createDotNpmrc()
{
    const npmrcPath = path.join(cwd, '.npmrc');
    if (!fs.existsSync(npmrcPath)) {
        fs.writeFileSync(npmrcPath, `package-lock=false`);
        console.log("Generated .npmrc");
    }
}

main();

